# The value of AppId uniquely identifies this application.
# Do not use the same AppId value in installers for other applications.
app_id: 640cd60e-8d74-444a-9bb9-d7a8eaf4a033
publisher: Remering
publisher_url: https://github.com/Remering/biome_matcher
display_name: Biome Matcher
create_desktop_icon: true
# See: https://jrsoftware.org/ishelp/index.php?topic=setup_defaultdirname
# install_dir_name: "D:\\HELLO-WORLD"
# This path is relative to the root directory of your project; The format of icon file must be ico, can not be png or others
# setup_icon_file: windows\runner\resources\app_icon.ico
locales:
  - en
  - zh