name: FastForge Build Dev

on:
    workflow_dispatch

jobs:
  build-windows-dev:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'
          channel: stable
      
      - name: Set up MSVC Build Tools
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Install Inno Setup
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install -y innosetup

      - name: Download Chinese Language Pack (Fix for Inno Setup)
        shell: powershell
        run: |
          $ErrorActionPreference = "Stop"
          
          # 强制使用 TLS 1.2 协议，确保下载连接安全和稳定
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
          
          $TargetDir = "C:\Program Files (x86)\Inno Setup 6\Languages"
          # 语言包的可靠下载链接
          $IslUrl = "https://raw.githubusercontent.com/kira-96/Inno-Setup-Chinese-Simplified-Translation/master/ChineseSimplified.isl"
          
          Write-Host "Downloading ChineseSimplified.isl to $TargetDir"
          if (-not (Test-Path $TargetDir)) { mkdir $TargetDir }
          
          # 使用 Invoke-WebRequest 下载，并设置 TimeoutSec 避免无限期卡住
          Invoke-WebRequest -Uri $IslUrl -OutFile "$TargetDir\ChineseSimplified.isl" -TimeoutSec 30
          Write-Host "Download complete."
          
      - name: Install Fastforge
        run: dart pub global activate fastforge

      - name: Build and release
        run: fastforge release --skip-clean	--name dev 

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist/