name: FastForge Build Dev

on:
    workflow_dispatch

jobs:
  build-windows-dev:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'
          channel: stable
      
      - name: Set up MSVC Build Tools
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Install Inno Setup
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install -y innosetup

      - name: Download Chinese Language Pack (Fix for Inno Setup)
        shell: powershell
        run: |
          # 确保脚本遇到错误时停止执行
          $ErrorActionPreference = "Stop"
          # 目标路径，这是 Inno Setup 默认寻找语言包的位置
          $TargetDir = "C:\Program Files (x86)\Inno Setup 6\Languages"
          # 语言包的可靠下载链接 (来自社区维护的 Inno Setup 简体中文翻译项目)
          $IslUrl = "https://raw.githubusercontent.com/kira-96/Inno-Setup-Chinese-Simplified-Translation/master/ChineseSimplified.isl"
          
          Write-Host "Creating target directory: $TargetDir"
          if (-not (Test-Path $TargetDir)) {
              mkdir $TargetDir
          }
          
          Write-Host "Downloading ChineseSimplified.isl to $TargetDir"
          # 使用 curl.exe 下载文件并保存到指定路径
          curl.exe -L $IslUrl -OutFile "$TargetDir\ChineseSimplified.isl"

      - name: Install Fastforge
        run: dart pub global activate fastforge

      - name: Build and release
        run: fastforge release --skip-clean	--name dev 

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist/